from praktikum.ingredient_types import INGREDIENT_TYPE_SAUCE, INGREDIENT_TYPE_FILLING

# Названия соусов
SAUCE_HOT = "hot sauce"
SAUCE_SOUR_CREAM = "sour cream"
SAUCE_KETCHUP = "ketchup"
SAUCE_BBQ = "bbq"
SAUCE_MAYO = "mayonnaise"

# Названия начинок
FILLING_CUTLET = "cutlet"
FILLING_CHEESE = "cheese"
FILLING_LETTUCE = "lettuce"
FILLING_TOMATO = "tomato"
FILLING_ONION = "onion"

# Цены ингредиентов
PRICE_SAUCE_HOT = 50
PRICE_SAUCE_SOUR_CREAM = 30
PRICE_SAUCE_KETCHUP = 25
PRICE_SAUCE_BBQ = 45
PRICE_SAUCE_MAYO = 20

PRICE_FILLING_CUTLET = 150
PRICE_FILLING_CHEESE = 80
PRICE_FILLING_LETTUCE = 30
PRICE_FILLING_TOMATO = 40
PRICE_FILLING_ONION = 25

# Ожидаемые строки в чеке для ингредиентов
RECEIPT_SAUCE_HOT = f"= sauce {SAUCE_HOT} ="
RECEIPT_SAUCE_SOUR_CREAM = f"= sauce {SAUCE_SOUR_CREAM} ="
RECEIPT_SAUCE_KETCHUP = f"= sauce {SAUCE_KETCHUP} ="
RECEIPT_FILLING_CUTLET = f"= filling {FILLING_CUTLET} ="
RECEIPT_FILLING_CHEESE = f"= filling {FILLING_CHEESE} ="

# Комбинации для параметризации (кортежи)
INGREDIENT_HOT_SAUCE = (INGREDIENT_TYPE_SAUCE, SAUCE_HOT, PRICE_SAUCE_HOT)
INGREDIENT_SOUR_CREAM = (INGREDIENT_TYPE_SAUCE, SAUCE_SOUR_CREAM, PRICE_SAUCE_SOUR_CREAM)
INGREDIENT_KETCHUP = (INGREDIENT_TYPE_SAUCE, SAUCE_KETCHUP, PRICE_SAUCE_KETCHUP)
INGREDIENT_CUTLET = (INGREDIENT_TYPE_FILLING, FILLING_CUTLET, PRICE_FILLING_CUTLET)
INGREDIENT_CHEESE = (INGREDIENT_TYPE_FILLING, FILLING_CHEESE, PRICE_FILLING_CHEESE)
